name: solvcon_install

on:
  push:
  pull_request:
  schedule:
    - cron: '21 17 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-18.04, macos-latest]

        fail-fast: false

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qqy install fakeroot debhelper locales \
                libffi6 \
                liblapack3 liblapack-dev

    - name: dependency (devenv)
      run: |
        git clone https://github.com/j8xixo12/devenv -b bzip2_enhance
        source ${GITHUB_WORKSPACE}/devenv/scripts/init
        devenv add prime
        devenv use prime
        devenv show
        devenv build sqlite
        devenv launch solvcon

    - name: show dependency
      run: |
        source ${GITHUB_WORKSPACE}/devenv/scripts/init
        devenv use prime
        devenv show
        export
        which gcc
        gcc --version
        which cmake
        cmake --version
        which python3
        python3 --version
        python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
        which gmsh

    - name: show python env
      run: |
        source ${GITHUB_WORKSPACE}/devenv/scripts/init
        devenv use prime
        devenv show
        which python3
        python3 --version
        python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
        python3 -c 'import sys ; print(sys.path)'
        echo "==============="
        echo "python globals:"
        python3 -c 'import numpy, solvcon ; print(globals())'
        echo "==============="
        echo "python locals:"
        python3 -c 'import numpy, solvcon ; print(locals())'
