#!/bin/env bash
#
# Copyright (C) 2011 Yung-Yu Chen <yyc@solvcon.net>.

set -e
source ${DEVENVROOT}/scripts/func.d/build_utils

pkgname=zlib
pkgbranch=${VERSION:-master}
pkgfull=${pkgname}-${pkgbranch}
install_dir=${DEVENVROOT}/usr/${DEVENVFLAVOR}

syncgit https://github.com/madler ${pkgname} ${pkgbranch} 

pushd ${DEVENVROOT}/src/${DEVENVFLAVOR}/${pkgfull} > /dev/null

# build.
buildcmd configure.log ./configure --prefix=${install_dir}
buildcmd make.log make -j ${NP}
buildcmd install.log make install

popd > /dev/null

# vim: set et nobomb ft=bash ff=unix fenc=utf8:
